Repository googleapis/gapic-generator-go, pull requests merged in 2021-08, with the labels that each got.

#725 bazel: add diregapic flag
  rules_go_gapic/go_gapic.bzl
Labels: automerge, cla: yes

#728 fix: rest pagination fixes
  internal/gengapic/genrest.go
  internal/gengapic/paging.go
  internal/gengapic/testdata/method_GetManyThings.want
  internal/gengapic/testdata/method_GetManyThingsOptional.want
Labels: cla: yes

#729 chore: remove deprecated protobuf v1 imports
  internal/gengapic/BUILD.bazel
  internal/gengapic/client_init_test.go
  internal/gengapic/example_test.go
  internal/gengapic/gengapic_test.go
  internal/gengapic/genrest_test.go
  internal/gengapic/helpers_test.go
  internal/gengapic/metadata_test.go
  internal/gengapic/mixins_test.go
  internal/gengapic/paging_test.go
  internal/gensample/BUILD.bazel
  internal/gensample/enum_test.go
  internal/gensample/gensample_test.go
  internal/gensample/inittree_test.go
  internal/grpc_service_config/BUILD.bazel
  internal/grpc_service_config/config_test.go
  internal/pbinfo/BUILD.bazel
  internal/pbinfo/pbinfo_test.go
Labels: cla: yes

#730 chore: add apidiff to showcase test
  .github/workflows/ci.yaml
  showcase/showcase.bash
Labels: automerge, cla: yes

#731 chore: remove gensample
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  README.md
  cmd/gen-go-sample/BUILD.bazel
  cmd/gen-go-sample/README.md
  cmd/gen-go-sample/main.go
  cmd/gen-go-sample/test.bash
  cmd/protoc-gen-go_cli/BUILD.bazel
  cmd/protoc-gen-go_cli/main.go
  cmd/protoc-gen-go_gapic/BUILD
  cmd/protoc-gen-go_gapic/main.go
  docker-entrypoint.sh
  internal/gengapic/options.go
  internal/gensample/BUILD.bazel
  internal/gensample/bytes.go
  internal/gensample/enum.go
  internal/gensample/enum_test.go
  internal/gensample/gapic.go
  internal/gensample/genmanifest.go
  internal/gensample/genmanifest_test.go
  internal/gensample/gensample.go
  internal/gensample/gensample_sampleconfig_test.go
  internal/gensample/gensample_test.go
  internal/gensample/inittree.go
  internal/gensample/inittree_test.go
  internal/gensample/out.go
  internal/gensample/paging.go
  internal/gensample/plugin.go
  internal/gensample/primval.go
  internal/gensample/resource.go
  internal/gensample/resource_test.go
  internal/gensample/sampmain.go
  internal/gensample/schema_v1p2/BUILD.bazel
  internal/gensample/schema_v1p2/schema.go
  internal/gensample/schema_v1p2/schema_test.go
  internal/gensample/testdata/manifest.want
  internal/gensample/testdata/sample_empty.want
  internal/gensample/testdata/sample_empty_object.want
  internal/gensample/testdata/sample_enum.want
  internal/gensample/testdata/sample_lro.want
  internal/gensample/testdata/sample_map_out.want
  internal/gensample/testdata/sample_paging.want
  internal/gensample/testdata/sample_response_map_field.want
  internal/gensample/testdata/sample_response_repeated_field.want
  internal/gensample/testdata/sample_unary.want
  internal/gensample/testdata/sample_write_file.want
  internal/gensample/typing.go
  rules_go_gapic/go_gapic.bzl
Labels: automerge, cla: yes

#733 gapic: include example in package doc overview
  internal/gengapic/doc_file.go
  internal/gengapic/doc_file_test.go
  internal/gengapic/example.go
  internal/gengapic/gengapic.go
  internal/gengapic/gengapic_test.go
  internal/gengapic/testdata/doc_file.want
  internal/gengapic/testdata/doc_file_alpha.want
  internal/gengapic/testdata/doc_file_beta.want
Labels: cla: yes

#741 chore: add pkg.go.dev link to request struct examples
  internal/gengapic/example.go
  internal/gengapic/testdata/doc_file.want
  internal/gengapic/testdata/doc_file_alpha.want
  internal/gengapic/testdata/doc_file_beta.want
  internal/gengapic/testdata/empty_example.want
  internal/gengapic/testdata/empty_example_grpc.want
  internal/gengapic/testdata/foo_example.want
  internal/gengapic/testdata/foo_example_rest.want
Labels: cla: yes, automerge

#744 gapic: exclude GET from custom op wrapping
  internal/gengapic/gengapic.go
  internal/gengapic/gengapic_test.go
  internal/gengapic/genrest.go
  internal/gengapic/genrest_test.go
  internal/gengapic/testdata/rest_CustomOp.want
Labels: cla: yes

#746 gapic: fix fields with nums
  internal/gengapic/gengapic_test.go
  internal/gengapic/genrest.go
  internal/gengapic/helpers.go
  internal/gengapic/helpers_test.go
  internal/gengapic/paging.go
Labels: cla: yes

#745 gapic: wrap errors from REST better
  internal/gengapic/genrest.go
  internal/gengapic/genrest_test.go
  internal/gengapic/testdata/rest_CustomOp.want
  showcase/echo_test.go
Labels: cla: yes

#734 chore: add compute regen
  .github/workflows/ci.yaml
Labels: cla: yes

#755 chore: disable renovate dep dashboard
  renovate.json
Labels: cla: yes, automerge

#754 gapic: exclude diregapic Wait RPC from op wrapping
  internal/gengapic/gengapic.go
  internal/gengapic/gengapic_test.go
Labels: cla: yes, automerge, breaking change allowed

#756 fix: do not generate sample method snippet for services without methods
  internal/gengapic/doc_file.go
  internal/gengapic/doc_file_test.go
  internal/gengapic/testdata/doc_file_alpha_emptyservice.want
  internal/gengapic/testdata/doc_file_beta_emptyservice.want
  internal/gengapic/testdata/doc_file_emptyservice.want
Labels: cla: yes, disable job: compute-regen

#759 gapic: fix compute wait wrapping logic
  internal/gengapic/custom_operation.go
  internal/gengapic/gengapic.go
  internal/gengapic/genrest.go
Labels: cla: yes, automerge, breaking change allowed
